name: TODO
description: TODO
inputs:
  owner:
    description: TODO
  repo:
    description: TODO
  name:
    description: TODO
runs:
  using: composite
  steps:
    - shell: bash
      run: |-
        ${{ github.action_path }}/bin/action \
          -owner "${{ inputs.owner }}" \
          -repo "${{ inputs.repo }}" \
          -name "${{ inputs.name }}" \
          -token "${{ github.token }}"
      env:
        GH_TOKEN: ${{ github.token }}
