name: Test
on:
  release:
    types:
      - published
  # Allow manual runs.
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: eigenbot-app/download-release@main
        with:
          owner: eigenbot-app
          repo: download-release
          name: download-release
          token: ${{ github.token }}
